### ISSUE TITLE
Build error in VTK on Windows

### ISSUE THREAD

**Issue by georgegerdin** [KitwareMedical/SlicerCAT#2]
The error is 

c:\slicercat\build\vtk\common\core\vtkMultiThreader.h(34): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

I understand the error is because VTK_USE_PTHREADS is erroneously set but I have no idea where to fix the error in this superbuild system.

Using Visual Studio Community 2017.

**Comment by sjh26** [comment]
Hi, sorry for the very slow response time.

The unistd.h file should not be used in a Windows build, that is a Unix only system header.  You should try re configuring and verifying that the windows build parameters are being passed down correctly.

**Comment by jcfr** [comment]
Closing. The issue has likely been fixed. 

Few comments:

* For creating custom application, consider using [KitwareMedical/SlicerCustomAppTemplate](https://github.com/KitwareMedical/SlicerCustomAppTemplate).

* To learn about the build requirement, see https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/index.html

* In early 2022, we also improved the `README` file of `SlicerCAT` (this project) to include a `Frequently Asked Questions` section. See https://github.com/KitwareMedical/SlicerCAT/pull/8
